### ISSUE TITLE
Cant compile cabbage on ubuntu 16.04

### ISSUE THREAD

**Issue by cjdg** [rorywalsh/cabbage_v1_old#19]
i try to compile but i get the following error:

CabbageMessageSystem.h:27:22: fatal error: csound.hpp:

**Comment by rorywalsh** [comment]
Sounds like you haven't installed Csound? Or if you have, the headers are not in the standard location. If that's the case you can change the include paths when you are building Cabbage. The steps involved are described in the README file in the Cabbage Builds/Linux folder.

**Comment by arthurtofani** [comment]
You can check in which this hpp file is installed by typing this: `dpkg -L libcsnd-dev
`

**Comment by rorywalsh** [comment]
I'm closing this because of lack of a response from the original poster..
