### ISSUE TITLE
Cabbage GUI syntax

### ISSUE THREAD

**Issue by nwhetsell** [rorywalsh/cabbage_v1_old#22]
I’m adding syntax highlighting of Cabbage elements in Csound files to [language-csound](https://github.com/nwhetsell/language-csound), and I have a few questions about Cabbage GUI syntax:

* What kinds of comments are available? It says [here](http://cabbageaudio.com/docs/cabbage_syntax/) that “Only ; type comments can be used in the Cabbage section of code, /`/ will not work.” I’m taking this to mean that this works:

    ```csound
    ; comment
    ```

    and these don’t work:

    ```csound
    // comment
    /* comment */
    ```

    Is this right?

* Are widget types and identifiers case sensitive?

* Widget types of `hslider3` and `vslider3` appear in the [`GUICtrlsArray`](https://github.com/rorywalsh/cabbage/search?q=GUICtrlsArray+path%3ASource+filename%3ACabbageGUIClass.h). Are these deprecated?

* Several widget types appear in the [`GUILayoutCtrlsArray`](https://github.com/rorywalsh/cabbage/search?q=GUILayoutCtrlsArray+path%3ASource+filename%3ACabbageGUIClass.h) but appear to be undocumented. Should I be highlighting these? Are any of these deprecated?

    * `directorylist`
    * `hostbpm`
    * `hostplaying`
    * `hostppqpos`
    * `hostrecording`
    * `hosttime`
    * `line`
    * `listbox`
    * `loadbutton`
    * `multitab`
    * `patmatrix`
    * `popupmenu`
    * `pvsview`
    * `recordbutton`
    * `snapshot`
    * `socketreceive`
    * `socketsend`
    * `source`
    * `sourcebutton`
    * `stepper`
    * `transport`

**Comment by rorywalsh** [comment]
Hi Nate. I'm currently rewriting the entire code base for Cabbage. I didn't want to mess up this repo so I started another one of the time being. It's probably best to work off that one. The following are all valid in Cabbage2:

https://github.com/rorywalsh/cabaiste/blob/master/Source/CabbageIds.h#L193-L207
https://github.com/rorywalsh/cabaiste/blob/master/Source/CabbageIds.h#L219-L241
https://github.com/rorywalsh/cabaiste/blob/master/Source/CabbageIds.h#L254-L352

You're right about comments, only

`; comment`

is accepted for now. Cabbage has is not case sensitive. That's just a throw back to early versions. Perhaps I should this latest version case sensitive, but I'd be afraid I would break users instruments.

**Comment by nwhetsell** [comment]
Awesome, thanks.

One last pair of questions: Are `hslider2` and `vslider2` still deprecated? And are `hslider3` and `vslider3` deprecated?

**Comment by rorywalsh** [comment]
Yeah, they're deprecated.

**Comment by nwhetsell** [comment]
Many thanks!
