### ISSUE TITLE
VST errors building Cabbage.

### ISSUE THREAD

**Issue by therealkitman** [rorywalsh/cabbage_v1_old#23]
Hi,
When building Cabbage under openSUSE 42.2 x64 with my command -

`./buildCabbage "/usr/local/include/csound" "/usr/local/lib" "~/MusicSoftware/VST3_SDK"`

I kept getting errors at this point -

`Compiling juce_audio_processors.cpp
Compiling juce_audio_utils.cpp
In file included from ../../JuceLibraryCode/modules/juce_audio_processors/juce_audio_processors.cpp:152:0:
../../JuceLibraryCode/modules/juce_audio_processors/format_types/juce_VSTPluginFormat.cpp:49:44: fatal error: pluginterfaces/vst2.x/aeffectx.h: No such file or directory
 #include "pluginterfaces/vst2.x/aeffectx.h"
                                            ^
compilation terminated.`

The issue is you need to put a copy of the VSTSDK pluginterfaces folder and all its subfolder contents in
`.../git/cabbage/JuceLibraryCode/modules/juce_audio_processors/format_types/pluginterfaces` so that the `juce_VSTPluginFormat.cpp` #include path is correct.

This has caught me out for a few other apps as well. Perhaps your README.txt install instructions need to be updated to mention this?

PS. Where do the export vst and lv2 files get saved as I can't find them?

Thanks,
Chris.

**Comment by cabbageaudio** [comment]
Putting the vst SDK in that directory might work, but it's definitely not
recommended. The best thing is to place the SDK in ~SDKs. The make files
should find everything after that. Alternatively, you can edit the paths in
the 3 make files to point to your custom location. Are you building from
the develop branch? I thought we had that issue fixed.

**Comment by therealkitman** [comment]
No I was building from the master branch. I have now pulled the development branch and am working with that. Get new errors now but that may be due to lack of dependencies in openSUSE which I am sorting through.

BTW - Does Cabbage need 32 or 64 bit dev files as the About  screen says "Cabbage(32bit)v1.1.07"?

**Comment by rorywalsh** [comment]
It builds as 64bit on most modern distros. You can ignore the popup.

**Comment by therealkitman** [comment]
Thanks.
