### ISSUE TITLE
Failed building VST and LV2 on linux

### ISSUE THREAD

**Issue by therealkitman** [rorywalsh/cabbage_v1_old#25]
Sorry Rory but this is a continuation of #24.

I did a fresh git install of the develop branch and attached the txt log of it's building.
1. It does not build the LV2 module. see line 709 in attached log.
2. VST building still complains about missing header files. see line 944 in log. My vst sdk in in `/home/chris/SDKs/VST3 SDK` as previously discussed. I only run `./buildCabbage` without passed parameters.

However Cabbage seems to be able to open and run csd files from the example folder (eg TR-808.csd).

I'll be joining the forum shortly to ask other linux user's experience :)

[cabbage.txt](https://github.com/rorywalsh/cabbage/files/800892/cabbage.txt)

**Comment by therealkitman** [comment]
Wait - in line 28 of ./buildCabbage you have spelled CabbagePluginEffectLV2 with a lower case 'v'
`	make -f MakefilePluginSynthLv2 -j8 CONFIG=Release`
I have edited to an upper case 'V' and I don;t get the error as stated in point 1 in the previous post.
However it fixes one issue with LV2 but the log file still has one complaint about the CabbagePluginEffectLV2.so file. 

> Compiling CabbageMessageSystem.cpp
> Linking CabbageHost
> cp: cannot stat './build/CabbagePluginEffectLV2.so': No such file or directory
> 


Seems to be related to that missing VST header issue in line 1195 in attached log file?
[cabbage2.txt](https://github.com/rorywalsh/cabbage/files/800937/cabbage2.txt)



> Compiling juce_VST_Wrapper.cpp
> ../../JuceLibraryCode/modules/juce_audio_plugin_client/VST/juce_VST_Wrapper.cpp:69:51: fatal error: public.sdk/source/vst2.x/audioeffectx.h: No such file or directory
>  #include <public.sdk/source/vst2.x/audioeffectx.h>
>                                                    ^
> compilation terminated.
> MakefilePluginEffectLV2:307: recipe for target 'build/intermediate/Release/juce_VST_Wrapper_bb62e93d.o' failed
> make: *** [build/intermediate/Release/juce_VST_Wrapper_bb62e93d.o] Error 1
> make: *** Waiting for unfinished jobs....
>

**Comment by rorywalsh** [comment]
I've replied to this issue on the Cabbage forum..

**Comment by therealkitman** [comment]
Hi,
I hope you have at least acknowledged the typo error in `buildCabbage` before I close this issue?

**Comment by rorywalsh** [comment]
I don't expect the issue to be closed until it's resolved ;) I've updated the makefile in question in the dev branch.

**Comment by therealkitman** [comment]
Thanks Rory. I thought you were moving this discussion to the forum. If you want me to build or test or experiment with code just let me know.
