### ISSUE TITLE
request: multistate button

### ISSUE THREAD

**Issue by jpnielsen** [rorywalsh/cabbage_v1_old#28]
I request that a "button" can have more than two states.

colour:0("colour") 
colour:1("colour") 
colour:2("colour") 

I own an APC40 from akai - In Ableton, the buttons change colour on each press (green - orange - red) - The colour of the light in the button is set with a midi message from the DAW. (http://www.akaipro.com/apc40map)

thanks
Jens Peter Nielsen

**Comment by rorywalsh** [comment]
I assume you figured out a way to do this? It can be done with the current button widget and a variable that will increment each time its pressed. Along with an identchannel() identifier to change the colour of the button. If you need an example let me know.
